//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliensOldEnemies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliensOldEnemies.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;/Images/angar.jpg&quot;/&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Темно. В тусклом свете аварийного освещения был виден большой квадратный ангар с высоким потолком.  Вдоль стены штабелями стоят несколько больших контейнеров.  В дальнем углу ангара находится автопогрузчик.&lt;/p&gt;
        ///&lt;p&gt;В боковой стене дверь,  ведущая в
        ///соседний Технический отсек.&lt;/p&gt;
        ///&lt;p&gt;Никого из обслуживающего персонала корабля не видно.  Хотя согласно правилам,  прибывших пассажиров должны
        ///встречать–  инженер технической службы и офицер безопасности.  Жарко.  Темпер [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/1_time_-1&quot;&gt;Остаться в отсеке(вам(-1) Время) – еще раз бросать кубик на событие.&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&apos;/6_time_-1_technik&apos;&gt;Использовать автопогрузчик, чтобы снять верхние контейнеры вниз и осмотреть их (вам (-1) Время) – требуется умение-техник. - 6&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&apos;/13&apos;&gt;Идти в Технический отсек - 13&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string a1_select {
            get {
                return ResourceManager.GetString("a1_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ответ Мак Коллинза- &lt;i&gt;«Температура на корабле постоянно повышается.  Скорее всего,  причина в поломке Реактора. &lt;a href=&apos;/7&apos;&gt;Если так пойдет и дальше,  через несколько часов, корабль может просто взорваться»&lt;/i&gt; - 7&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ответ Мак Коллинза - &lt;br&gt;&lt;i&gt;«В каждом отсеке установлены коммуникаторы.  Но после того,  как все это началось.  Многие коммуникаторы вышли из строя.  Из криков,  которые были слышны через них,  я понял,  что произошло нападение каких-то инопланетных тварей.  Судя по переговорам экипажа,  это какие-то гигантские насекомые.  &lt;a href=&quot;/7&quot;&gt;Кажется, они плюются кислотой и их очень трудно убить».&lt;/i&gt; - 7&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string a11 {
            get {
                return ResourceManager.GetString("a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ответ Мак Коллинза - &lt;br&gt;&lt;i&gt;«Первое нападение произошло в отсеке «Оранжерея». Откуда там взялись эти твари–  непонятно!  Когда наш корабль стоял в доке на космической станции «Альфа-17»  работники Корпорации «ФитоСкай»  провели профилактику растений и сменили весь гидропон в оранжерее. Вроде бы все было в порядке. 
        ///&lt;br&gt;
        ///&lt;a href=&quot;/7&quot;&gt;Но об этом скорее нужно расспросить нашего биолога Роберта Фула…  хм-м…если он еще жив»&lt;/i&gt; - 7&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string a12 {
            get {
                return ResourceManager.GetString("a12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;/Images/techroom.jpg&quot;/&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Вокруг вдоль стен стальные стеллажи с ящиками и запчастями. В этом отсеке занимаются починкой агрегатов и механизмов.  Возле дальней стены находится забаррикадированная дверь, ведущая в соседний отсек Пищеблока.  Слева под потолком виден выход воздуховода.&lt;/p&gt;.
        /// </summary>
        public static string a13 {
            get {
                return ResourceManager.GetString("a13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/13_time_-1&quot;&gt;Остаться в отсеке (вам (-1) Время) – еще раз бросать кубик на событие.&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/17&quot;&gt;Идти в отсек Пищеблока- 17&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/18_time_-2&quot;&gt;Лезть в воздуховод – до отсека  Лазарет (-2 Времени) - 18&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/19_time_-4&quot;&gt;Лезть в воздуховод – до отсека Каюты (-4 Времени) – 19&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/20_time_-6&quot;&gt;Лезть в воздуховод – до Инженерного отсека(-6 Времени) – 20&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/1&quot;&gt;Идти в отсек Ангара - 1&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;
        ///&lt;br&gt;.
        /// </summary>
        public static string a13_select {
            get {
                return ResourceManager.GetString("a13_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Технический отсек- Событие:&lt;/b&gt;&lt;br&gt;
        ///&lt;p&gt;Среди прочего мусора вы находите безжизненное серое тело Чужого-краба.  Его трупик
        ///выглядит окаменевшим.&lt;/p&gt;
        ///.
        /// </summary>
        public static string a14 {
            get {
                return ResourceManager.GetString("a14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Технический отсек- Событие:&lt;/b&gt;&lt;br&gt;
        ///&lt;p&gt;Кажется,  температура на корабле повысилась.  Становится жарковато.  Всем членам вашей
        ///команды (-1) Жизнь.&lt;/p&gt;
        ///&lt;a href=&quot;/13&quot;&gt;С системами корабля явно что-то не в порядке. – 13&lt;/a&gt;.
        /// </summary>
        public static string a15 {
            get {
                return ResourceManager.GetString("a15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Технический отсек- Событие:&lt;/b&gt;&lt;br&gt;
        ///&lt;p&gt;Внезапно по коммуникационному селектору корабля вы слышите &lt;br&gt;– &lt;i&gt;«Помогите! Кто меня слышит?!  Говорит &lt;b&gt;Роберт Фул&lt;/b&gt;. Я обнаружил источник появления этих тварей –  это находится в отсеке Утилизации.  Черт!!  Что это?!  О боже!  Это невозможно!!»&lt;/i&gt; -  вы слышите несколько выстрелов,  скрежет,  визг и человеческие крики.&lt;/p&gt;
        ///&lt;a href=&quot;/13&quot;&gt;Все.  Связь оборвалась. Тишина. - 13&lt;/a&gt;.
        /// </summary>
        public static string a16 {
            get {
                return ResourceManager.GetString("a16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;В этом отсеке хранятся пищевые запасы экипажа,  и находится общая столовая.  Вокруг валяются перевернутые столы и стулья,  зловонные остатки еды и мусор.  Вы видите несколько растерзанных до неузнаваемости человеческих тел.
        ///Отсюда двери ведут в Коридор«С», в Лазарет и в Технический отсек.&lt;/p&gt;&lt;br&gt;.
        /// </summary>
        public static string a17 {
            get {
                return ResourceManager.GetString("a17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/17_time_-1&quot;&gt;Остаться в этом отсеке- (вам (-1) Время) – еще раз бросать кубик на событие.&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&apos;/13&apos;&gt;Идти в Технический отсек – 13&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&apos;/60&apos;&gt;Идти в Коридор «С» – 60&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&apos;/18&apos;&gt;Идти в Лазарет - 18&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string a17_select {
            get {
                return ResourceManager.GetString("a17_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Горит тусклое аварийное освещение. Под потолком есть входное отверстие воздуховода.  В отсеке лазарета несколько полупрозрачных переборок.  За переборками койки для пациентов. Несколько шкафов у стен. Везде беспорядок.&lt;/p&gt;
        ///&lt;p&gt;В углу стоит большой стационарный рентген-аппарат.&lt;/p&gt;
        ///&lt;p&gt;Рядом операционный стол с роботом-доктором для оказания первой помощи, - но он сломан.&lt;/p&gt;
        ///&lt;p&gt;Стол робота-доктора в одном месте насквозь прожжен.  На краях дыры застыл пузырями керамопластик.  Пол тоже прожжен насквозь.  П [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a18 {
            get {
                return ResourceManager.GetString("a18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;/33&quot;&gt;Идти в отсек Грузовой Лифт – 33&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/17&quot;&gt;Идти в отсек Пищеблока – 17&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/13_time-2&quot;&gt;Лезть по воздуховоду в Технический отсек (-2  Времени) – 13&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/20_time-5&quot;&gt;Лезть по воздуховоду в Инженерный отсек (-5 Времени) – 20&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/19_time-3&quot;&gt;Лезть по воздуховоду в отсек Кают (-3 Времени) - 19&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string a18_select {
            get {
                return ResourceManager.GetString("a18_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Вдоль стен тянутся двухъярусные койки и узкие шкафы. На полу перевернутые табуреты и разбросанные личные вещи экипажа. В углу отсека баррикада из мебели и шкафов.&lt;/p&gt;.
        /// </summary>
        public static string a19 {
            get {
                return ResourceManager.GetString("a19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;b&gt;Ваши дальнейшие действия?&lt;/b&gt;&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/19_time-1&quot;&gt;Остаться пока в отсеке – бросьте снова кубик события (-1 Время).&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/71&quot;&gt;Идти в отсек Арсенала - 71&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/60&quot;&gt;Идти в отсек Коридор «С» - 60&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/20_time-2&quot;&gt;Лезть в воздуховод и ползти до Инженерного отсека (-2 Времени) – 20&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/18_time-3&quot;&gt;Лезть в воздуховод и ползти до Лазарета (-3 Времени) – 18&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/13_time-5&quot;&gt;Лезть в воздуховод и ползти до [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a19_select {
            get {
                return ResourceManager.GetString("a19_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Вы почувствовали,  что температура воздуха в отсеке повышается.  Приборы на вашем бронекостюме показывают,  что температура на корабле явно выше нормы.  Всем членам вашей команды (-1)  Жизнь.  Причина такой жары пока неизвестна.  Если температура будет повышаться и дальше,  то это может грозить вашей жизни и жизни
        ///экипажа.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;a href=&quot;/1&quot;&gt;Могут выйти из строя системы корабля. - 1&lt;/a&gt;.
        /// </summary>
        public static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Это помещение используют как грузовой отсек. Здесь же находится пульт управления техническими системами корабля. Под потолком есть выход воздуховода.&lt;/p&gt;.
        /// </summary>
        public static string a20 {
            get {
                return ResourceManager.GetString("a20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Лазарет – Вы замечаете на полу кровавый след, который ведет к одному из железных шкафов возле стены. Двери шкафа прикрыты.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;b&gt;Ваши действия?&lt;/b&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/24&quot;&gt;Расстрелять шкаф с расстояния – 24&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/25&quot;&gt;Подойти и открыть шкаф – 25&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string a21 {
            get {
                return ResourceManager.GetString("a21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Лазарет– Вы замечаете на одной из коек неподвижно лежащую молодую женщину. Ее
        ///лицо бледно-серого цвета.  Кажется,  она не дышит.  Пульс не прощупывается.  У нее на
        ///бэйдже написано– Сюзанна Мур(навигатор).&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/27_time-1&quot;&gt;В лазарете есть стационарный рентген-аппарат, и вы можете проверить наличие внутри
        ///тела этой женщины – зародыша Чужого (-1  Время) – 27;&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/18&quot;&gt;Если не хотите тратить на это время, – вернитесь на – 18&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string a22 {
            get {
                return ResourceManager.GetString("a22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Лазарет– Вдруг вы слышите как кто-то, громыхая, лезет по воздухопроводу к выходу в
        ///отсек лазарета.  Слышен приближающийся грохот металлической обшивки воздуховода.
        ///Черная блестящая фигура Чужого уже начала высовываться из отверстия…!!&lt;/p&gt;
        ///&lt;br&gt;&lt;b&gt;Ваши действия?&lt;/b&gt;&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/29&quot;&gt;Стрелять в Чужого – 29&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/30&quot;&gt;Не стрелять и ждать – 30&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/31&quot;&gt;Отступить в отсек Пищеблок – 31&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/32&quot;&gt;Отступить в отсек Лифт – 32&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string a23 {
            get {
                return ResourceManager.GetString("a23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;От ваших пуль дверца шкафа быстро превращается в дырявое сито с рваными дырами. Из-
        ///за двери вы слышите душераздирающие крики. Кто-то дергается там внутри. Шкаф
        ///бешено сотрясается. Дверь открывается и из шкафа вываливается труп пожилого
        ///мужчины. Он лежит на полу без движения и под ним быстро растекается лужа крови. Вы
        ///видите, что одна его нога, выше колена, плотно перебинтована медицинским пластырем.
        ///По-видимому, этот человек был ранее ранен, но смог сам оказать себе медицинскую
        ///помощь.&lt;/p&gt;&lt;br&gt;
        ///&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a24 {
            get {
                return ResourceManager.GetString("a24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Вы осторожно открываете шкаф и видите там спрятавшегося пожилого мужчину. Он до
        ///смерти напуган. Одна его нога перебинтована.&lt;/p&gt;
        ///&lt;i&gt;&lt;p&gt;«Вы,...вы…вы - кто?» – заикаясь спрашивает вас мужчина – «Вы из группы спасения?
        ///Господи, неужели мне повезло! Нужно скорее убираться отсюда. Эти ужасные твари
        ///всех убивают».&lt;/p&gt;&lt;/i&gt;
        ///&lt;p&gt;Вы видите на бэйдже мужчины надпись – Ливенгауп (доктор).&lt;/p&gt;&lt;br&gt;
        ///&lt;b&gt;Ваши действия?&lt;/b&gt;&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/74_time-1&quot;&gt;Опросить доктора (-1 Времени) – 74&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a25 {
            get {
                return ResourceManager.GetString("a25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;a href=&quot;/18&quot;&gt;Мертвый доктор – Нет зародыша Чужого – 18&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string a26 {
            get {
                return ResourceManager.GetString("a26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Дверь,  ведущая в соседний отсек,  отошла в бок,  и в проеме появился человек в
        ///синем комбинезоне.  На его груди была эмблема Компании«СпейсКом».  Он помахал вам
        ///рукой, и торопливо побежал к вам навстречу.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;b&gt;Ваши действия?&lt;/b&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/4&quot;&gt;стрелять в него - 4&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/5&quot;&gt;не стрелять в него - 5&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Человек упал подкошенный вашим метким выстрелом. Вы осмотрели его труп. На
        ///куртке комбинезона вы видите бэйдж с надписью– Мак Коллинз (техник).&lt;/p&gt;&lt;br&gt;
        ///&lt;a href=&apos;/1_chipplata&apos;&gt;Обыскав его тело, вы находите одну чип-плату. - 1&lt;/a&gt;.
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Пищеблок – Из-за угла на вас выскочил какой-то мужчина с большим кухонным тесаком в
        ///руке. С безумными глазами и криками он бросился на вас.&lt;/p&gt;&lt;br&gt;
        ///&lt;p&gt;Ваши действия?&lt;/p&gt;
        ///&lt;p&gt;Пищеблок – Из-за угла на вас выскочил какой-то мужчина с большим кухонным тесаком в
        ///руке. С безумными глазами и криками он бросился на вас.&lt;/p&gt;&lt;br&gt;
        ///&lt;p&gt;Ваши действия?&lt;/p&gt;.
        /// </summary>
        public static string a41 {
            get {
                return ResourceManager.GetString("a41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;В его теле есть зародыш Чужого.&lt;/p&gt;&lt;br&gt;.
        /// </summary>
        public static string a47 {
            get {
                return ResourceManager.GetString("a47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;i&gt;– «Слава богу,  вы прибыли, - взволнованно сказал он, опасливо поглядывая назад–
        ///У нас тут чрезвычайная ситуация.  Меня зовут Мак Коллинз.  Я техник.  Боюсь,  что я
        ///последний из выживших членов экипажа.  Там внутри корабля происходит что-то
        ///ужасное.  Я ничего не понимаю.  Я лишь слышал по внутреннему коммуникатору крики
        ///людей.  Они звали на помощь….  Они умирали!  Потом все стихло.  Я боялся и остался на
        ///Техническом складе.  Там я забаррикадировал все двери и ждал.  Слава богу,  вы
        ///прибыли…».&lt;/i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Какие вопросы вы хотите задать Мак Коллинзу? (за каждый вопрос вам(-1) Время)&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;/8_time_-1&quot;&gt;Где находится дипломат Артур Харрисон? – 8&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/9_time_-1&quot;&gt;Как проходит система воздуховодов на корабле? - 9&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/10_time_-1&quot;&gt;Почему на корабле высокая температура? – 10&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/11_time_-1&quot;&gt;Что происходит на корабле? – 11&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/12_time_-1&quot;&gt;Откуда могли взяться на корабле Чужие? – 12&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;/1&quot;&gt;Больше [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ответ Мак Коллинза- &lt;i&gt;«Дипломат Артур Харрисон проживал в отсеке Кают.  Но он так же был допущен и в командную Рубку.&lt;br&gt;
        ///&lt;a href=&quot;/7&quot;&gt;Вполне возможно,  что в момент,  когда все началось, он находился в отсеке Пищеблока»&lt;/i&gt; - 7&lt;/a&gt;&lt;/p&gt;&lt;br&gt;.
        /// </summary>
        public static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ответ Мак Коллинза - &lt;i&gt;«Вот схема воздуховодов. Она имеет выходы лишь в некоторых отсеках корабля.  По воздуховодам человек может пробраться только ползком.  Для каждого уровня-этажа существует отдельная система воздуховодов. &lt;br&gt; 
        ///&lt;a href=&quot;/7&quot;&gt;По воздуховоду верхнего уровня невозможно попасть на нижний уровень(см. схему)»&lt;/i&gt; - 7&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;2154 год. Система Фарингейта. &lt;/p&gt;&lt;/br&gt;
        ///&lt;p&gt;Грузовой корабль серии МХ – «Бафуто» дрейфовал на орбите планеты Боргезе-9.&lt;/p&gt;
        ///&lt;p&gt;Вот уже два дня в бескрайние просторы космоса с корабля поступали сигналы SOS.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Система Фарингейта, Астероид G-7. Военно-патрульная база «Пегас».&lt;/p&gt;
        ///&lt;p&gt;В конференц-зале полковник Дж. Балтимор проводил брифинг перед группой бойцов:&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;«Пять часов назад мы получили сигнал SOS с грузового корабля серии МХ – «Бафуто».&lt;/p&gt;
        ///&lt;p&gt;Корабль находится на орбите пла [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;«Предполагаемый противник – нарочито холодным тоном продолжил полковник – Это терраноиды, известные в широких военных кругах по кличке «Чужие».&lt;p&gt;
        ///&lt;p&gt;Терраноиды подразделяются на несколько видов – «яйцо» с зародышем внутри, членистоногий Краб, Чужой-солдат, Чужой-офицер, Мать-Королева. Терраноиды мутируют из одной форму в другую именно в этой последовательности.&lt;/p&gt;
        ///&lt;p&gt;Они используют людей или как живой корм. Или как инкубатор для откладывания внутрь человеческого тела небольших спор-зародышей Чужих.&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Шатл дернулся, коснувшись посадочной платформы ангара грузового корабля серии МХ– «Бафуто». Шлюзовые ворота корабля закрылись. Отсек ангара с шумом заполнился кислородом. Красные аварийные огни потухли.  Системы стыковки грузового корабля работали в норме.
        ///&lt;p&gt;Механический голос бортового компьютера произнес- «Стыковка завершена.
        ///Команда может покинуть шатл».&lt;/p&gt;
        ///&lt;p&gt;Мощные гидроусилители беззвучно опустили спусковой трап шатла,  и ваша
        ///команда вышла в ангар.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;a href=&quot;/1&quot;&gt;Далее...&lt;/a&gt;.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
