//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliensOldEnemies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliensOldEnemies.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;2154 год. Система Фарингейта. &lt;/p&gt;&lt;/br&gt;
        ///&lt;p&gt;Грузовой корабль серии МХ – «Бафуто» дрейфовал на орбите планеты Боргезе-9.&lt;/p&gt;
        ///&lt;p&gt;Вот уже два дня в бескрайние просторы космоса с корабля поступали сигналы SOS.&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;Система Фарингейта, Астероид G-7. Военно-патрульная база «Пегас».&lt;/p&gt;
        ///&lt;p&gt;В конференц-зале полковник Дж. Балтимор проводил брифинг перед группой бойцов:&lt;/p&gt;
        ///&lt;br&gt;
        ///&lt;p&gt;«Пять часов назад мы получили сигнал SOS с грузового корабля серии МХ – «Бафуто».&lt;/p&gt;
        ///&lt;p&gt;Корабль находится на орбите пла [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Предполагаемый противник – нарочито холодным тоном продолжил полковник – Это терраноиды, известные в широких военных кругах по кличке «Чужие». 
        ///Терраноиды подразделяются на несколько видов – «яйцо» с зародышем внутри, членистоногий Краб, Чужой-солдат, Чужой-офицер, Мать-Королева. Терраноиды мутируют из одной форму в другую именно в этой последовательности. 
        ///Они используют людей или как живой корм. Или как инкубатор для откладывания внутрь человеческого тела небольших спор-зародышей Чужих.
        ///Твари крайне а [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
    }
}
